version: '3'

services:
  api:
    container_name: posts-postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - PORT=3100
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PW=postgres      
    ports:
      - 3100:3100
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - DB_USER=postgres
      - DB_PASS=postgres